package:
  name: nmse_utils
  version: 0.0.1

source:
  git_rev: master
  git_url: git@github.com:kevinwhitham/nmse_utils.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home:
