package:
  name: nmse_utils
  version: 0.0.2

source:
  git_rev: master
  git_url: git@github.com:kevinwhitham/nmse_utils.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandas

test:
  imports:
    - nmse_utils

about:
  home: https://github.com/kevinwhitham/nms_utils
