package:
  name: nmse
  version: 0.0.1

source:
  git_rev: 0.0.1
  git_url: https://github.com/kwhitham/nmse

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
